spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 10
  datasource:
    url: jdbc:mysql://124.70.166.238:10066/beidou_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 'shen2020HAI!@#'
biz:
  scTime: 30000

staticPath: D:/file/